### ISSUE TITLE
PHP is dead

### ISSUE THREAD

**Issue by putra4648** [adamjatim/kartar-kelurahan-ampel#2]
hari gini kok masih pake PHP?
pake shopify dong

**Comment by adamjatim** [comment]
emang lu udah sampe mana main shopify nya

**Comment by putra4648** [comment]
> emang lu udah sampe mana main shopify nya

Gak main sebenarnya aku bang gak level soalnya hehehehe

**Comment by adamjatim** [comment]
apalah walawe
